# Generated by Django 3.0.5 on 2022-05-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreg',
            name='file_path1',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='file_path2',
        ),
    ]
