# Generated by Django 3.0.5 on 2022-05-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getin', '0002_auto_20220526_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='type',
            new_name='Role',
        ),
    ]
