# Generated by Django 3.0.5 on 2022-05-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getin', '0003_auto_20220526_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='password1',
        ),
    ]
