# Generated by Django 3.0.5 on 2022-05-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getin', '0004_auto_20220526_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='fb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'fb',
            },
        ),
    ]
