# Generated by Django 3.0.5 on 2022-06-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getin', '0006_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
