# Generated by Django 3.0.5 on 2022-06-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getin', '0008_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
