# Generated by Django 3.0.5 on 2022-06-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getin', '0009_auto_20220609_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/%y%m%d'),
        ),
    ]
