# Generated by Django 3.0.5 on 2022-06-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getin', '0010_auto_20220612_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.ImageField(blank=True, null=True, upload_to='license/%y%m%d')),
                ('Role', models.CharField(blank=True, default='staff', max_length=100, null=True)),
                ('Exp', models.CharField(blank=True, max_length=100, null=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('housename', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'staffreg',
            },
        ),
    ]
