# Generated by Django 3.0.5 on 2022-06-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getin', '0011_staffreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffreg',
            name='dob',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
