# Generated by Django 3.0.5 on 2022-06-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getin', '0012_staffreg_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffreg',
            name='license',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/%y%m%d'),
        ),
    ]
