# Generated by Django 3.0.5 on 2022-06-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getin', '0013_auto_20220615_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffreg',
            name='license',
            field=models.ImageField(blank=True, null=True, upload_to='license/%y%m%d'),
        ),
    ]
