# Generated by Django 3.0.5 on 2022-06-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getin', '0014_auto_20220618_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffreg',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=100, null=True),
        ),
    ]
