# Generated by Django 3.0.5 on 2022-06-27 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getin', '0016_fb_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fb',
            name='date',
        ),
        migrations.AddField(
            model_name='fb',
            name='currentdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
